fix: website deployment script
Signed-off-by: Steven E Wright <StevenEWright@users.noreply.github.com>

diff --git a/ci b/ci
--- a/ci
+++ b/ci
@@ -31,7 +31,7 @@ cat << "EOF"
  └─────────────────────────────────────────────────────────────────────────────┘
 EOF
 
-if [ -z "$(npm install -s)" ]; then
+if [ -z "$(npm install --ignore-scripts -s)" ]; then
 
   echo -e $Green
   echo "  ✅ Dependencies installed"
@@ -92,6 +92,25 @@ else
   echo "  💩 Linting failed!"
   echo -e $Color_Off
   echo "  📝 Try running: npm run lint:fix - are your husky scripts broken?"
+fi
+
+cat << "EOF"
+ ┌─────────────────────────────────────────────────────────────────────────────┐
+ │ 🌐 Website...                                                               │
+ └─────────────────────────────────────────────────────────────────────────────┘
+
+EOF
+
+size_result=0
+./website gen || size_result=$?
+if [ $size_result -eq 0 ]; then
+  echo -e $Green
+  echo "  ✅ Website built!"
+  echo -e $Color_Off
+else
+  echo -e $Red
+  echo "  ❌ An error occurred while building the website."
+  echo -e $Color_Off
 fi
 
 cat << "EOF"
